define([], function() {
	return function(text) {
		if (typeof locale === "undefined") {
			locale = document.documentElement.getAttribute('lang');
			if (typeof locale === "undefined") {
				var locale = "en-us";
			}
		}
		var locales = {
			"en-us": {
				"alarme": "alarm",
				"declenchement": "trigger",
				"defaut pression": "pressure fault",
				"defaut gaz": "gas fault",
				"Transformateur": "Transformer"
			},
			"fr-fr": {
				"Acquittal": "Acquittement",
				"Address": "Adresse",
				"All": "Tous",
				"at": "à",
				"Average": "Moyenne",
				"Absolución": "Acquittement",
				"Copy": "Copier",
				"During": "Pendant",
				"Evolution of temperatures": "Évolution des températures",
				"First occurence the : ": "Première occurence le : ",
				"Module ID": "ID du module",
				"No module name": "Pas de nom de module",
				"Not set": "Pas défini",
				"Projection": "Projection",
				"The": "Le",
				"to": "à",
				"Since": "Depuis",
				"Solved the : ": "Résolu le : ",
				"Still ongoing": "Toujours en cours",
				"Stop monitoring this module?": "Retirer la surveillance de ce module ?",
				/* Alerts */
				"Acquittal": "Acquittement",
				"alarme": "alarme",
				"declenchement": "déclenchement",
				"defaut gaz": "défaut gaz",
				"defaut pression": "défaut pression",
				"defaut temperature": "défaut de température",
				"transformateur": "transformateur",
				"temperature": "température",
				/* Admin */
				"Delete the account of ": "Supprimer le compte de ",
				"Delete the company ": "Supprimer le groupe ",
				"Details": "Détails",
				"Hide this notification for the customer too?": "Masquer cette notification pour le client aussi ?",
				"Key": "Clé",
				"Modify the module": "Modifier le module",
				"Please move": "Veuillez déplacer",
				" this module": " ce module",
				" these modules": " ces modules",
				" this user": " cet utilisateur",
				" these users": " ces utilisateurs",
				" to another group": " vers un autre groupe",
				"Unlink the module": "Dissocier le module",
				"Value": "Valeur",
				/* Notifications */
				"Alert": "Alerte",
				"Alerts": "Alertes",
				"An action on your part may be needed.": "Une action de votre part est peut-être nécessaire.",
				"Consult": "Consulter",
				"New notifications": "Nouvelles notifications",
				"New notification": "Nouvelle notification",
				"Seen": "Vu"
			},
			"es-es": {
				"Address": "Dirección",
				"All": "Todas",
				"at": "a",
				"Assoluzione": "Acquittement",
				"Copy": "Copiar",
				"During": "Durante",
				"Evolution of temperatures": "Evolución de la temperatura",
				"First occurence the : ": "Primera aparición del : ",
				"Module ID": "ID del módulo",
				"No module name": "Sin nombre de módulo",
				"Not set": "No establecido",
				"Projection": "Proyección",
				"The": "El",
				"to": "al",
				"Since": "Ya que",
				"Solved the : ": "Resuelto el : ",
				"Still ongoing": "Aún en curso",
				"Stop monitoring this module?": "¿Eliminar la supervisión de este módulo?",
				/* alerts */
				"Acquittal": "Absolución",
				"alarme": "alarma",
				"declenchement": "gatillo",
				"defaut pression": "falla de presión",
				"defaut gaz": "falla de gas",
				"defaut temperature": "falla de temperatura",
				"temperature": "temperatura",
				"Transformateur": "Transformador",
				"temperature": "temperatura",
				/* admin */
				"Delete the account of ": "¿Eliminar la cuenta de ",
				"Delete the company ": "¿Eliminar grupo ",
				"Details": "Detalles",
				"Hide this notification for the customer too?": "¿Ocultar esta notificación para el cliente también?",
				"Key": "Llave",
				"Modify the module": "Modificar el módulo",
				"Please move": "Por favor muévete",
				" this module": " este módulo",
				" these modules": " estos módulos",
				" this user": " este usuario",
				" these users": " estos usuarios",
				" to another group": " a otro grupo",
				"Unlink the module": "Desvincular el módulo",
				"Value": "Valor",
				/* Notifications */
				"Alert": "Alerta",
				"Alerts": "Alertas",
				"An action on your part may be needed.": "Tal vez sea necesaria alguna acción de su parte.",
				"Consult": "Consultar",
				"New notifications": "Notificaciones nuevas",
				"New notification": "Nueva notificación",
				"Seen": "Visto"
			},
			"it-it": {
				"Address": "Indirizzo",
				"All": "Tutti",
				"at": "a",
				"Assoluzione": "Acquittement",
				"Copy": "Copia",
				"During": "Durante",
				"Evolution of temperatures": "Evoluzione della temperatura",
				"First occurence the : ": "Prima occorrenza il : ",
				"Module ID": "ID modulo",
				"No module name": "Nessun nome del modulo",
				"Not set": "Non impostato",
				"Projection": "Proiezione",
				"The": "Il",
				"to": "a",
				"Since": "Per",
				"Still ongoing": "Ancora in corso",
				"Solved the : ": "Risolto il : ",
				"Stop monitoring this module?": "Rimuovere il monitoraggio da questo modulo?",
				/* alerts */
				"Acquittal": "Assoluzione",
				"alarme": "Allarmami",
				"declenchement": "grilletto",
				"defaut pression": "difetto di pressione",
				"defaut gaz": "guasto del gas",
				"defaut temperature": "guasto del temperatura",
				"temperature": "temperatura",
				"Transformateur": "Trasformatore",
				"temperature": "temperatura",
				/* admin */
				"Delete the account of ": "Elimina il conto di ",
				"Delete the company ": "Rimuovere gruppo Ab ",
				"Details": "Dettagli",
				"Hide this notification for the customer too?": "Nascondere questa notifica anche per il cliente?",
				"Key": "Chiave",
				"Modify the module": "Modifica il modulo",
				"Please move": "Per favore muoviti",
				" this module": " questo modulo",
				" these modules": " questi moduli",
				" this user": " questo utente",
				" these users": " questi utenti",
				" to another group": " a otro grupo",
				"Unlink the module": "Scollega il modulo",
				"Value": "Valore",
				/* Notifications */
				"Alert": "Avviso",
				"Alerts": "Avvisi",
				"An action on your part may be needed.": "Forse è necessaria un'azione da parte tua.",
				"Consult": "Consultare",
				"New notifications": "nuova notifica",
				"New notification": "nuove notifiche",
				"Seen": "Vidi"
			},
			"de-de": {
				"Address": "Adresse",
				"All": "Alles",
				"at": "beim",
				"Copy": "Kopieren",
				"During": "Während",
				"Evolution of temperatures": "Entwicklung der Temperaturen",
				"First occurence the : ": "Erstes Auftreten der:",
				"Module ID": "Modul-ID",
				"No module name": "Kein Modulname",
				"Not set": "Nicht festgelegt",
				"The": "Das",
				"to": "zu",
				"Since": "Schon seit",
				"Solved the : ": "Gelöst das:",
				"Still ongoing": "Noch nicht abgeschlossen",
				"Stop monitoring this module?": "Überwachung dieses Moduls beenden?",
				/* alerts */
				"Acquittal": "Freispruch",
				"alarme": "alarme",
				"declenchement": "Deklenchement",
				"defaut pression": "defaut pression",
				"defaut gaz": "defaut gaz",
				"defaut gaz": "defaut temperatur",
				"temperature": "Temperatur",
				"Transformateur": "Transformateur",
				/* admin */
				"Delete the account of ": "Löschen Sie das Konto von",
				"Delete the company ": "Löschen Sie die Firma",
				"Details": "Einzelheiten",
				"Hide this notification for the customer too?": "Diese Benachrichtigung auch für den Kunden ausblenden?",
				"Key": "Schlüssel",
				"Modify the module": "Ändern Sie das Modul",
				"Please move": "Bitte bewegen",
				" this module": "  dieses Modul",
				" these modules": "  diese Module",
				" this user": "  dieser Benutzer",
				" these users": "  diese Benutzer",
				" to another group": "  zu einer anderen Gruppe",
				"Unlink the module": "Trennen Sie das Modul",
				"Value": "Wert",
				/* Notifications */
				"Alert": "Aufmerksam",
				"Alerts": "Warnungen",
				"An action on your part may be needed.": "Möglicherweise ist eine Aktion von Ihrer Seite erforderlich.",
				"Consult": "Konsultieren",
				"New notifications": "Neue Benachrichtigungen",
				"New notification": "Neue Benachrichtigung",
				"Seen": "Geseheno"
			},
			"nl-nl": {
				"Address": "Adres",
				"All": "Alle",
				"at": "Bij",
				"Copy": "Kopiëren",
				"During": "Gedurende",
				"Evolution of temperatures": "Evolutie van temperaturen",
				"First occurence the : ": "Eerste keer de:",
				"Module ID": "Module-ID",
				"No module name": "Geen modulenaam",
				"Not set": "Niet ingesteld",
				"The": "De",
				"to": "naar",
				"Since": "Sinds",
				"Solved the : ": "Opgelost:",
				"Still ongoing": "Nog steeds aan de gang",
				"Stop monitoring this module?": "Stoppen met het monitoren van deze module?",
				/* alerts */
				"Acquittal": "Vrijspraak",
				"alarme": "schrik",
				"declenchement": "declinatie",
				"defaut pression": "defaut druk",
				"defaut gaz": "defaut gas",
				"defaut gaz": "defaut temperatuur",
				"temperature": "temperatuur",
				"Transformateur": "Transformateur",
				/* admin */
				"Delete the account of ": "Verwijder het account van",
				"Delete the company ": "Verwijder het bedrijf",
				"Details": "Details",
				"Hide this notification for the customer too?": "Deze melding ook voor de klant verbergen?",
				"Key": "Sleutel",
				"Modify the module": "Wijzig de module",
				"Please move": "Schuif alsjeblieft op",
				" this module": "  deze module",
				" these modules": "  deze modules",
				" this user": "  deze gebruiker",
				" these users": "  deze gebruikers",
				" to another group": "  naar een andere groep",
				"Unlink the module": "Ontkoppel de module",
				"Value": "Waarde",
				/* Notifications */
				"Alert": "Alert",
				"Alerts": "Waarschuwingen",
				"An action on your part may be needed.": "Mogelijk moet u iets doen.",
				"Consult": "Raadplegen",
				"New notifications": "Nieuwe notificaties",
				"New notification": "Nieuwe melding",
				"Seen": "Gezieno"
			}
		}
		if (typeof locales[locale] === 'undefined' || typeof locales[locale][text] === "undefined") {
			return text;
		}
		return locales[locale][text];
	}
});